version: '3.8'

services:
  plex-container:
    image: lscr.io/linuxserver/plex:latest
    environment:
      - PUID=1000
      - PGID=1000
      - VERSION=docker
      - TZ=Europe/Paris
      - PLEX_CLAIM="${TOKEN_PLEX}"
    volumes:
        - ./dist/library:/config
        - ./dist/tvseries:/tv
        - ./dist/movies:/movies
    restart: unless-stopped
    ports:
      - "32400:32400"
      - "3005:3005"
      - "8324:8324"
      - "32469:32469"
      - "1900:1900/udp"
      - "32410:32410/udp"
      - "32412:32412/udp"
      - "32413:32413/udp"
      - "32414:32414/udp"
