version: '3.8'

services:
  overseer-container:
    image: ghcr.io/sct/overseerr:latest
    hostname: overserr.duckdns.org
    container_name: overseer-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ../dist/overseer/config:/config
    ports:
      - "5055:5055"
    restart: unless-stopped
    depends_on:
      - swagg-container
    networks:
      - network-project


  deluge-openvpn-container:
    image: ebrianne/docker-deluge-openvpn:latest
    environment:
        - OPENVPN_PROVIDER=PIA
        - OPENVPN_CONFIG=france
        - OPENVPN_USERNAME=user
        - OPENVPN_PASSWORD=pass
        - LOCAL_NETWORK=192.168.0.0/16
    cap_add:
        - NET_ADMIN
    sysctls:
        - net.ipv6.conf.all.disable_ipv6=1
    ports:
      - '8112:8112'
    volumes:
      - ../dist/deluge/config:/config
      - ../dist/deluge/downloads:/downloads
    restart: unless-stopped
    depends_on:
      - swagg-container
      - bazarr-container
    networks:
      - network-project


  swagg-container:
    image: linuxserver/swag:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
      - SUBDOMAINS=wildcard
      - VALIDATION=duckdns
      - DUCKDNSTOKEN=${TOKEN_DUCKDNS:? The docker compose file need a generated a DuckDNS token to work properly}
    volumes:
      - ../dist/swagg/config/:/config
    ports:
      - "443:443"
    restart: unless-stopped
    networks:
      - network-project


  authelia-swagg:
    image: ghcr.io/authelia/authelia:latest
    user: "1000:1000"
    environment:
      - TZ=Europe/Paris
    volumes:
      - ../dist/authelia/config/:/config
    restart: unless-stopped
    networks:
      - network-project


  prowlarr-container:
    image: lscr.io/linuxserver/prowlarr:develop
    container_name: prowlarr-container
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../dist/prowlarr:/config
    ports:
      - "9696:9696"
    restart: unless-stopped
    depends_on:
      - swagg-container
    networks:
      - network-project

  bazarr-container:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
    volumes:
      - ../dist/bazarr/config:/config
      - ../dist/bazarr/movies:/movies
      - ../dist/bazarr/tv:/tv
    ports:
      - "6767:6767"
    depends_on:
      - radarr-container
      - sonarr-container
      - swagg-container
    restart: unless-stopped
    networks:
      - network-project

networks:
  network-project:
    external: true
